server:
  port: 8000

spring:
  mvc:
    view:
      prefix: /template/
      suffix: .html

  resources:
    static-locations: classpath:/static/

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dont_sell_salt?charsetEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: salt1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        id:
          new-generator-mapping: false
        format_sql: true
      show-sql: true

  thymeleaf:
    cache: false
    encoding: UTF-8
    servlet:
      content-type: text/html;charset=UTF-8

  jackson:
    serialization:
      fail-on-empty-beans: false

  http:
    encoding:
      charset: UTF-8